<?php
$z[0]=Array("list","{dede:arclist  typeid='11'  row='5'  titlelen='100' addfields='img1,price' channelid='19'}\r\n\r\n	<div id=\"big\">\r\n\r\n		<div class=\"left\">\r\n		  <div class=\"left_top\">\r\n			<p>[field:title/]</p>\r\n			</div>\r\n\r\n		  <div class=\"left_buttom\">\r\n			<a href='[field:arcurl/]'><p>тд╤ах╚нд</p></a>\r\n			</div>\r\n		</div>\r\n\r\n		<div class=\"right\">\r\n			<img src=\"[field:img1/]\" width=100% height=\"300px\">\r\n		</div>\r\n\r\n\r\n	</div>\r\n {/dede:arclist}",2,546);
$z[0][4]['pagesize']="30";
$z[0][4]['col']="1";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";
$z[0][4]['channel']="19";
$z[0][4]['att']="a";

?>