--{dede:list  pagesize='30' col='1' titlelen='60' orderby='pubdate' orderway='desc' 
 channel='19'  att='a' }{dede:arclist  typeid='11'  row='5'  titlelen='100' addfields='img1,price' channelid='19'}

	<div id="big">

		<div class="left">
		  <div class="left_top">
			<p>[field:title/]</p>
			</div>

		  <div class="left_buttom">
			<a href='[field:arcurl/]'><p>ÔÄ¶ÁÈ«ÎÄ</p></a>
			</div>
		</div>

		<div class="right">
			<img src="[field:img1/]" width=100% height="300px">
		</div>


	</div>
 {/dede:arclist}{/dede:list}--