<?php
$z[0]=Array("bt","\r\n",2,156);
$z[0][4]['itemname']="标题";
$z[0][4]['autofield']="1";
$z[0][4]['notsend']="0";
$z[0][4]['type']="text";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="0";
$z[0][4]['default']="十大名茶 · 杭州";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("fbsj","\r\n",159,324);
$z[1][4]['itemname']="发布时间";
$z[1][4]['autofield']="1";
$z[1][4]['notsend']="0";
$z[1][4]['type']="text";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="0";
$z[1][4]['default']="发布时间：2019-5-20";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";

?>