<field:body itemname="ÏêÏ¸½éÉÜ" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	
<field:price itemname="³öÊÛ¼Û¸ñ" autofield="1" notsend="0" type="float" isnull="true" islist="1" default="£¤500.00/kg"  maxlength="" page="">
	
</field:price>
	
	
<field:brand itemname="ÎïÁ÷" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="×îÔçÃ÷Ôç10£º00ÅäËÍ"  maxlength="250" page="">
	
</field:brand>
	
<field:units itemname="¼ÆÁ¿µ¥Î»" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="kg"  maxlength="250" page="">
	
</field:units>
	
	
	
	
	
<field:img1 itemname="Í¼Æ¬1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img1>








<field:img2 itemname="Í¼Æ¬2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img2>


<field:img3 itemname="Í¼Æ¬3" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img3>

<field:img4 itemname="Í¼Æ¬4" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img4>

<field:img5 itemname="Í¼Æ¬5" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img5>

<field:img6 itemname="Í¼Æ¬6" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img6>


<field:img11 itemname="²âÊÔÓÃ11" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:img11>

