<?php
$z[0]=Array("list","{dede:arclist  typeid='3' row='12'  titlelen='68'  orderby='pubdate' addfields='img1,price' channelid='6'}\r\n    	<li class=\"piece\">\r\n			<img src=\"[field:img1/]\" width=\"263px\" height=\"230px\">\r\n            <p>[field:title/]</p>\r\n			<hr color=\"#b5c3a5\" noshade>\r\n            <p>￥[field:price /]/kg元</p>\r\n			<p align=\"right\"><a href='[field:arcurl/]'>+加入购物车</a></p>\r\n        </li>\r\n{/dede:arclist}",0,519);
$z[0][4]['pagesize']="30";
$z[0][4]['col']="1";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";
$z[0][4]['channel']="6";
$z[0][4]['att']="h";

?>