<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	
<field:price itemname="出售价格" autofield="1" notsend="0" type="float" isnull="true" islist="1" default="￥500.00/kg"  maxlength="" page="">
	
</field:price>

	
	
<field:brand itemname="物流" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="最早明早10：00配送"  maxlength="250" page="">
	
</field:brand>
	
<field:units itemname="计量单位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="kg"  maxlength="250" page="">
	
</field:units>
	

	

	

	

	

<field:img1 itemname="图片1" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img1>

<field:img2 itemname="图片2" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img2>

<field:img3 itemname="图片3" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img3>

