<?php
$z[0]=Array("list","<div class=\"piece1\"> \r\n            <div>[field:title/]</div>\r\n            <div><hr color=\"#b5c3a5\" noshade></div>\r\n            <div>\r\n            	<div>￥500元/kg</div>\r\n                <div class=\"add\"><p align=\"right\"><a href=\"shop_article.htm\">+加入购物车</a></p></div>\r\n            </div>\r\n\r\n        </div>",2,418);
$z[0][4]['pagesize']="30";
$z[0][4]['col']="1";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";
$z[0][4]['att']="h";

?>