<?php
$z[0]=Array("list","<div class=\"shopimg\">\r\n              \r\n            	<img src=\"http://localhost/tea/templets/default/images/shop_list_cup_04.png\" width=\"263px\" height=\"230px\">\r\n                <a href='[field:arcurl/]'><img src=\"[field:img1/]\"  class=\"tupian\" width=\"263\" height=\"230\" /> </a>\r\n            </div>\r\n            <div>[field:title/]</div>\r\n            <div><hr color=\"#b5c3a5\" noshade></div>\r\n            <div>\r\n            	<div>￥[field:price /]元/kg</div>\r\n                <div class=\"add\"><p align=\"right\"><a href=\"shop_article.htm\">+加入购物车</a></p></div>\r\n            </div>",0,697);
$z[0][4]['pagesize']="30";
$z[0][4]['col']="1";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";
$z[0][4]['channel']="6";
$z[0][4]['att']="f";

?>