
<field:cy_img itemname="茶叶图片" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cy_img>


<field:cy_mc itemname="茶叶名称" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="西湖龙井"  maxlength="250" page="">
</field:cy_mc>

<field:cy_jg itemname="茶叶价格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="￥500.00/kg"  maxlength="250" page="">
</field:cy_jg>

<field:cy_gwc itemname="加入购物车" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="+加入购物车"  maxlength="250" page="">
</field:cy_gwc>
