{dede:list  pagesize='30' col='1' titlelen='60' orderby='pubdate' orderway='desc' 
 att='f' }<div class="shopimg">
                <a href='[field:arcurl/]'><img src="[field:img1/]"  class="tupian" width="263" height="230" /></a>
            <div>[field:title/]</div>
            <div><hr color="#b5c3a5" noshade></div>
            <div>
            	<div>￥[field:price /]元/kg</div>
                <div class="add"><p align="right"><a href="shop_article.htm">+加入购物车</a></p></div>
            </div>
 </div>{/dede:list}