<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['articleurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",16,174);
$z[0][4]['runphp']="yes";
$z[1]=Array("articleurl","",190,209);
$z[2]=Array("title","",225,239);
$z[3]=Array("pubdate","",298,344);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",373,387);
$z[5]=Array("scores","",416,431);
$z[6]=Array("description","",477,497);

?>