
<field:cy_img itemname="²èÒ¶Í¼Æ¬" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cy_img>


<field:cy_mc itemname="²èÒ¶Ãû³Æ" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="Î÷ºþÁú¾®"  maxlength="250" page="">
</field:cy_mc>

<field:cy_jg itemname="²èÒ¶¼Û¸ñ" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="£¤500.00/kg"  maxlength="250" page="">
</field:cy_jg>

<field:cy_gwc itemname="¼ÓÈë¹ºÎï³µ" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="+¼ÓÈë¹ºÎï³µ"  maxlength="250" page="">
</field:cy_gwc>

<field:img1 itemname="Í¼Æ¬1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img1>

<field:img2 itemname="Í¼Æ¬2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img2>



<field:img3 itemname="Í¼Æ¬3" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img3>
