
<field:bt itemname="标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="十大名茶 · 杭州"  maxlength="250" page="">
</field:bt>

<field:fbsj itemname="发布时间" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="发布时间：2019-5-20"  maxlength="250" page="">
</field:fbsj>

<field:wznr itemname="文章内容" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="“中国茶都”杭州，处处有好茶。


“杭州十大名茶”的是——

西湖龙井、径山茶、千岛玉叶、雪水云绿、天目青顶、千岛银珍、安顶云雾、湘湖龙井、天尊贡芽、鸠坑毛尖"  maxlength="250" page="">
</field:wznr>







<field:img1 itemname="图片1" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:img1>
