<?php
$z[0]=Array("list","{dede:arclist  typeid='12'  row='1'  titlelen='118' addfields='img1,price' channelid='19'}\r\n      <img src=\"[field:img1/]\" width=\"1024\" height=\"625\"><br />\r\n       {/dede:arclist}",2,301);
$z[0][4]['pagesize']="30";
$z[0][4]['col']="1";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";
$z[0][4]['channel']="19";
$z[0][4]['att']="a";

?>