<?php
$z[0]=Array("list","<div class=\"piece1\"> \r\n        	<div class=\"shopimg\">\r\n                 <a href='[field:arcurl/]'><img src=\"[field:img1/]\"  class=\"tupian\" width=\"263\" height=\"230\" /> </a>\r\n            </div>\r\n            <div>[field:title/]</div>\r\n            <div><hr color=\"#b5c3a5\" noshade></div>\r\n            <div>\r\n            	<div>￥[field:price /]元/kg</div>\r\n                <div class=\"add\"><p align=\"right\"><a href=\"shop_article.htm\">+加入购物车</a></p></div>\r\n            </div>\r\n        </div>",0,623);
$z[0][4]['pagesize']="30";
$z[0][4]['col']="4";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";
$z[0][4]['type']="image";
$z[0][4]['channel']="6";
$z[0][4]['att']="f";

?>