<div class="shopimg">
           <!--<img src="http://localhost/tea/templets/default/images/shop_list_cup_05.png" width="263px" height="230px">-->
           <a href="http://localhost/tea/a/gaodian/2019/0614/78.html?1560848474"><img src="[field:img1/]"  class="tupian" width="263" height="230" /> </a>
     
           </div>
            <div>[field:title/]</div>
            <div><hr color="#b5c3a5" noshade></div>
            <div>
            	<div>￥[field:price /]元/kg</div>
                <div class="add"><p align="right"><a href="http://localhost/tea/a/gaodian/2019/0614/78.html?1560848474">+加入购物车</a></p></div>
            </div>