<div class="shopimg">
              
            	<!--<img src="http://localhost/tea/templets/default/images/shop_list_cup_04.png" width="263px" height="230px">-->
                <a href='[field:arcurl/]'><img src="[field:cup1/]"  class="tupian" width="263" height="230" /> </a>
            </div>
            <div><a href='[field:arcurl/]'>[field:title/]</a></div>
            <div><hr color="#b5c3a5" noshade></div>
            <div>
            	<div>￥[field:price /]/kg</div>
                <div class="add"><p align="right"><a href="shop_article.htm">+加入购物车</a></p></div>
            </div>