<div><img src="[field:cup1/]" width="263" height="230" /><br /><a href='[field:arcurl/]'>[field:title/]</a><br />会员价：<span>[field:trueprice /]元</span></div>
        {/


    <div class="buttom">
    	<div class="piece1"> 
             {dede:arclist  typeid='8' row='1' addfields='img1,price' channelid='6' idlist='38'}
        	<div class="shopimg">
              
            	<!--<img src="http://localhost/tea/templets/default/images/shop_list_cup_04.png" width="263px" height="230px">-->
                <a href='[field:arcurl/]'><img src="[field:img1/]"  class="tupian" width="263" height="230" /> </a>
            </div>
            <div>[field:title/]</div>
            <div><hr color="#b5c3a5" noshade></div>
            <div>
            	<div>￥[field:price /]元/kg</div>
                <div class="add"><p align='[field:arcurl/]'hop_article.htm">+加入购物车</a></p></div>
            </div>