<?php
$z[0]=Array("global","",607,635);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",652,671);
$z[1][4]['name']="title";
$z[2]=Array("global","",672,698);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",743,772);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",816,874);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",2149,2184);
$z[5][4]['filename']="head.htm";
$z[6]=Array("arclist","\r\n    	<li class=\"piece\">\r\n			<img src=\"[field:img1/]\" width=\"263px\" height=\"230px\">\r\n            <p>[field:title/]</p>\r\n			<hr color=\"#b5c3a5\" noshade>\r\n            <p>￥[field:price /]/kg元</p>\r\n			<p align=\"right\"><a href='[field:arcurl/]'>+加入购物车</a></p>\r\n        </li>\r\n",2309,2691);
$z[6][4]['typeid']="2";
$z[6][4]['row']="12";
$z[6][4]['titlelen']="60";
$z[6][4]['addfields']="img1,price";
$z[6][4]['channelid']="6";
$z[7]=Array("include","",6379,6416);
$z[7][4]['filename']="footer.htm";

?>