<?php
$z[0]=Array("global","",614,642);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",659,678);
$z[1][4]['name']="title";
$z[2]=Array("global","",679,705);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",750,779);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",823,881);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",2163,2198);
$z[5][4]['filename']="head.htm";
$z[6]=Array("include","",3094,3131);
$z[6][4]['filename']="footer.htm";

?>