<?php
$z[0]=Array("global","",612,640);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",657,676);
$z[1][4]['name']="title";
$z[2]=Array("global","",677,703);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",748,777);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",821,879);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",2154,2189);
$z[5][4]['filename']="head.htm";
$z[6]=Array("arclist","\r\n\r\n	<div id=\"big\">\r\n\r\n		<div class=\"left\">\r\n		  <div class=\"left_top\">\r\n			<p>[field:title/]</p>\r\n			</div>\r\n\r\n		  <div class=\"left_buttom\">\r\n			<a href='[field:arcurl/]'><p>тд╤ах╚нд</p></a>\r\n			</div>\r\n		</div>\r\n\r\n		<div class=\"right\">\r\n			<img src=\"[field:img1/]\" width=100% height=\"300px\">\r\n		</div>\r\n\r\n\r\n	</div>\r\n ",2310,2734);
$z[6][4]['typeid']="11";
$z[6][4]['row']="5";
$z[6][4]['titlelen']="100";
$z[6][4]['addfields']="img1,price";
$z[6][4]['channelid']="19";
$z[7]=Array("include","",4771,4808);
$z[7][4]['filename']="footer.htm";

?>