<?php
$z[0]=Array("global","",609,637);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",654,673);
$z[1][4]['name']="title";
$z[2]=Array("global","",674,700);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",745,774);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",818,876);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",2151,2186);
$z[5][4]['filename']="head.htm";
$z[6]=Array("arclist","\r\n        	<div class=\"shopimg\">\r\n              \r\n            	<!--<img src=\"http://localhost/tea/templets/default/images/shop_list_cup_04.png\" width=\"263px\" height=\"230px\">-->\r\n                <a href='[field:arcurl/]'><img src=\"[field:img1/]\"  class=\"tupian\" width=\"263\" height=\"230\" /> </a>\r\n            </div>\r\n            <div>[field:title/]</div>\r\n            <div><hr color=\"#b5c3a5\" noshade></div>\r\n            <div>\r\n            	<div>￥[field:price /]元/kg</div>\r\n                <div class=\"add\"><p align=\"right\"><a href=\"shop_article.htm\">+加入购物车</a></p></div>\r\n            </div>\r\n              ",2330,3040);
$z[6][4]['typeid']="3";
$z[6][4]['row']="1";
$z[6][4]['addfields']="img1,price";
$z[6][4]['channelid']="3";
$z[6][4]['idlist']="68";
$z[7]=Array("arclist","\r\n        	<div class=\"shopimg\">\r\n           <!--<img src=\"http://localhost/tea/templets/default/images/shop_list_cup_05.png\" width=\"263px\" height=\"230px\">-->\r\n           <a href='[field:arcurl/]'><img src=\"[field:img1/]\"  class=\"tupian\" width=\"263\" height=\"230\" /> </a>\r\n     \r\n           </div>\r\n            <div>[field:title/]</div>\r\n            <div><hr color=\"#b5c3a5\" noshade></div>\r\n            <div>\r\n            	<div>￥[field:price /]元/kg</div>\r\n                <div class=\"add\"><p align=\"right\"><a href=\"shop_article.htm\">+加入购物车</a></p></div>\r\n            </div>\r\n            ",3123,3814);
$z[7][4]['typeid']="3";
$z[7][4]['row']="1";
$z[7][4]['addfields']="img1,price";
$z[7][4]['channelid']="6";
$z[7][4]['idlist']="69";
$z[8]=Array("arclist","\r\n        	<div class=\"shopimg\">\r\n           <img src=\"http://localhost/tea/templets/default/images/shop_list_cup_05.png\" width=\"263px\" height=\"230px\">\r\n           <a href='[field:arcurl/]'><!--<img src=\"[field:img2/]\"  class=\"tupian\" width=\"263\" height=\"230\" /> --></a>\r\n     \r\n           </div>\r\n            <div>[field:title/]</div>\r\n            <div><hr color=\"#b5c3a5\" noshade></div>\r\n            <div>\r\n            	<div>￥[field:price /]元/kg</div>\r\n                <div class=\"add\"><p align=\"right\"><a href=\"shop_article.htm\">+加入购物车</a></p></div>\r\n            </div>\r\n            ",3882,4573);
$z[8][4]['typeid']="3";
$z[8][4]['row']="1";
$z[8][4]['addfields']="img2,price";
$z[8][4]['channelid']="6";
$z[8][4]['idlist']="70";
$z[9]=Array("include","",8033,8070);
$z[9][4]['filename']="footer.htm";

?>