<?php
$z[0]=Array("global","",618,646);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",663,682);
$z[1][4]['name']="title";
$z[2]=Array("global","",683,709);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",754,783);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",827,885);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",2167,2202);
$z[5][4]['filename']="head.htm";
$z[6]=Array("arclist","\r\n    	<li class=\"piece\">\r\n			<img src=\"[field:img1/]\" width=\"263px\" height=\"230px\">\r\n            <p>[field:title/]</p>\r\n			<hr color=\"#b5c3a5\" noshade>\r\n            <p>￥[field:price /]/kg元</p>\r\n			<p align=\"right\"><a href='[field:arcurl/]' class='clj'>+加入购物车</a></p>\r\n        </li>\r\n",2327,2721);
$z[6][4]['typeid']="1";
$z[6][4]['row']="12";
$z[6][4]['titlelen']="76";
$z[6][4]['addfields']="img1,price";
$z[6][4]['channelid']="6";
$z[7]=Array("include","",6397,6434);
$z[7][4]['filename']="footer.htm";

?>